name: http-tools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.12', '3.13']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install httptools and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        pip install -e .
    - name: Lint with flake8
      run: |
        tox -e lint
    - name: Bandit
      run: |
        tox -e bandit
    - name: Run
      run: |
        httptools -h
    - name: Clean Up
      run: |
        tox -e clean
